apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: skupper-operator
  namespace: olm
spec:
  grpcPodConfig:
    securityContextConfig: restricted
  image: quay.io/skupper/skupper-operator-index:v1.4.0-rc2
  sourceType: grpc
