apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: skupper-operator
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/skupper/skupper-operator-index:v1.3.0
  grpcPodConfig:
    securityContextConfig: restricted
