apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: my-namespace
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: skupper-operator
  source: skupper-operator
  sourceNamespace: olm
  startingCSV: skupper-operator.v1.1.0
